version: '3.8'

services:
  minecraft_server:
    build: .
    ports:
      - "25565:25565"
    environment:
      MEMORY: 4G
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'